buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        //noinspection AndroidGradlePluginVersion
        //classpath 'com.android.tools.build:gradle:7.4.1'    // Qt 6.5.3
        //classpath 'com.android.tools.build:gradle:8.6.0'    // >= Qt 6.8.x
        //classpath 'com.android.tools.build:gradle:8.8.0'    // Qt 6.10.x
        classpath 'com.android.tools.build:gradle:9.0.0'    // Qt 6.11.x
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.3.0"
    }
}

repositories {
    google()
    mavenCentral()
}

apply plugin: qtGradlePluginType          // Qt >= 6.8.x
//apply plugin: 'com.android.application'     // Qt 6.5.3

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
//    implementation 'com.google.android.material:material:1.12.0'
    implementation 'com.google.android.material:material:1.14.0'
//    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.appcompat:appcompat:1.7.1'
//    implementation 'androidx.core:core:1.13.1'
    implementation 'androidx.core:core:1.17.0'
//    implementation 'androidx.preference:preference:1.1.0'
    implementation 'androidx.preference:preference:1.2.1'
}

android {
    /*******************************************************
     * The following variables:
     * - androidBuildToolsVersion,
     * - androidCompileSdkVersion
     * - qtAndroidDir - holds the path to qt android files
     *                   needed to build any Qt application
     *                   on Android.
     * - qtGradlePluginType - whether to build an app or a library
     *
     * are defined in gradle.properties file. This file is
     * updated by QtCreator and androiddeployqt tools.
     * Changing them manually might break the compilation!
     *******************************************************/

    // namespace androidPackageName                 // >= Qt 6.8.x --> Doesn't work!
    namespace 'org.qtproject.theosys'            // For individual setting
    compileSdkVersion androidCompileSdkVersion
    buildToolsVersion androidBuildToolsVersion
    ndkVersion androidNdkVersion

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = [qtAndroidDir + '/src', 'src', 'java']
            aidl.srcDirs = [qtAndroidDir + '/src', 'src', 'aidl']
            res.srcDirs = [qtAndroidDir + '/res', 'res']
            resources.srcDirs = ['resources', 'ressources', 'res']
            renderscript.srcDirs = ['src']
            assets.srcDirs = ['assets']
            jniLibs.srcDirs = ['libs']
       }
    }

    tasks.withType(JavaCompile) {
        options.incremental = true
        options.compilerArgs += ['-Xlint:all']
    }

    compileOptions {
//        sourceCompatibility JavaVersion.VERSION_1_8     // <= Qt 6.10.x
//        targetCompatibility JavaVersion.VERSION_1_8     // <= Qt 6.10.x
        sourceCompatibility JavaVersion.VERSION_17      // >= Qt 6.11.x
        targetCompatibility JavaVersion.VERSION_17      // >= Qt 6.11.x
    }

    lintOptions {
        abortOnError false
    }

    // Do not compress Qt binary resources file
    aaptOptions {
        noCompress 'rcc'
    }

    defaultConfig {
        applicationId "org.qtproject.theosys"
        resConfig "en"
        minSdkVersion qtMinSdkVersion
        targetSdkVersion qtTargetSdkVersion
        ndk.abiFilters = qtTargetAbiList.split(",")
        versionCode 5
        versionName "2.0.2"
    }

    packagingOptions {
        // Extract native libraries from the APK
        jniLibs {
            useLegacyPackaging = true
        }
        doNotStrip '*/mips/*.so'
        doNotStrip '*/mips64/*.so'
        doNotStrip '*/armeabi-v7a/*.so'
        doNotStrip '*/arm64-v8a/*.so'
        doNotStrip '*/i686/*.so'
        doNotStrip '*/x86/*.so'
        doNotStrip '*/x86_64/*.so'
    }
}
